### PR TITLE
Retryer

### PR DESCRIPTION
**Pull request by ljwolf**
This adds functionality to wait/retry between web requests. 

This is necessary for some map APIs, especially when downloading large/high-detail tilesets. 

This makes contextily kind of like a general purpose tile downloader for any API in the tile-url format, and I've found it extremely handy to work with rate-limited scientific APIs.

### CODE REVIEW

**Comment by ljwolf** [comment]
Hmm, strange; works locally, but I removed `six.BytesIO` for `io.BytesIO`, a three-only construct. 

I think this may have something to do with using `six.BytesIO` rather than the python3 builtin `io.BytesIO`.  Maybe `six` doesn't implement context handling.

**Comment by darribas** [comment]
I've finally had a look at the functionality, this is great. If you add (passing) tests, I'll merge this. Hopefully it can make it to the upcoming `rc`!

**Comment by ljwolf** [comment]
Not sure why this closed, but I had to reopen this to get the merge commit to show. 

Also, not sure how to mock this functionality in a unittest.

**Comment by darribas** [comment]
OK fair enough. I guess it is tested it at least works in any other method that pulls down tiles. One more thing, should we then add `requests` to the `requirements.txt`? It currently works so I imagine it's required by other libraries (`geopy`?) but it'd be good to have the explicit requirement. I'll merge afterwards.

**Comment by ljwolf** [comment]
I don't think requests is required by geopy, but it's used in a large amount of web-touching code. I also use it in cenpy. 

I mainly like it for the `raise_for_status()` functionality. 

I've added it to the requirements.

**Comment by darribas** [comment]
Cool!

**Pull request merged**
