### PR TITLE
Add option to catch tiles locally without additional requirements

### PR DESCRIPTION
**Pull request by uvchik**
Some server reject requests from python scripts. In my case this happened when I try to use the default OSM tile server. But I was able to download the tile via the web-browser.

https://a.tile.openstreetmap.org/tileZ/tileX/tileY.png

Therefore, I added an option to download the tiles manually (using the web-browser) and use the local files afterwards.

In case the server responses normally the tiles will be downloaded automatically and the local tiles will be used the next run. This will speed up the process and reduces server usage.

You can use this function by passing a path name where the files will be stored. If you do not pass a path name everything will remain as it is now.

If you like the idea I could add tests. Feel free to correct typos, I am not a native speaker.

### CODE REVIEW

**Comment by ljwolf** [comment]
Can you post the exact request failures you're getting? We may need to provide a user agent string when we [run `requests.get()`](https://github.com/darribas/contextily/blob/master/contextily/tile.py#L194), since some APIs require that now.

**Comment by uvchik** [comment]
I use the helper function from [geopandas](https://geopandas.readthedocs.io/en/latest/gallery/plotting_basemap_background.html#contextily-helper-function), extended with the path parameter:

```python
def add_basemap(ax, zoom, path=None, alpha=1.0,
                url='https://c.tile.openstreetmap.org'):
    url = '/'.join(s.strip('/') for s in [url, '/tileZ/tileX/tileY.png'])
    xmin, xmax, ymin, ymax = ax.axis()
    basemap, extent = ctx.bounds2img(xmin, ymin, xmax, ymax, zoom=zoom,
                                     url=url, path=path)
    ax.imshow(basemap, extent=extent, interpolation='bilinear', alpha=alpha)
    # restore original x/y limits
    ax.axis((xmin, xmax, ymin, ymax))
```

I get the following error but not only once but all the time:

```python
Traceback (most recent call last):
  File "~/my_plot.py", line 67, in <module>
    add_basemap(ax, zoom=map_zoom, path=my_path, alpha=map_alpha, url=osm_url)
  File "~/my_plot.py", line 20, in add_basemap
    url=url, path=path)
  File "~/git-projects/contextily/contextily/tile.py", line 165, in bounds2img
    image = _fetch_tile(tile_url, wait, max_retries)
  File "~/git-projects/contextily/contextily/tile.py", line 211, in _fetch_tile
    print(request.raise_for_status())
  File "~/.python_virtualenv/my_venv/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://a.tile.openstreetmap.org/15/17212/10490.png
```

**Comment by ljwolf** [comment]
Gotcha, would [`bounds2raster` do what this does?](https://github.com/darribas/contextily/pull/79/files#diff-0715663df5d779dfcab6104f769a5de5R18)

**Comment by uvchik** [comment]
Actually I like the variant to cache the files with the same function and API. I reverted the PEP changes and I removed the not so elegant print statements. Now the impact on the existing code is minimal and the new function works just fine. For high resolutions you get an immense speed up after the first run. You do not have to do anything just pass a path to the function where to cache the tiles.

If you move your section a little bit to the east, west, north or south you can use most of your cached files and add just the new ones.

Secondly the `bounds2raster` function does not work for me. I get the following error.

```python
Traceback (most recent call last):
  File "~/my_plot.py", line 73, in <module>
    add_basemap(ax, zoom=map_zoom, path=my_path, alpha=map_alpha, url=osm_url)
  File "~/my_plot.py", line 24, in add_basemap
    url=url, path=path)
  File "~/git-projects/contextily/contextily/tile.py", line 88, in bounds2raster
    crs='epsg:3857', transform=transform)
  File "~/.python_virtualenv/my_env/lib/python3.5/site-packages/rasterio/env.py", line 430, in wrapper
    return f(*args, **kwds)
  File "~/.python_virtualenv/my_env/lib/python3.5/site-packages/rasterio/__init__.py", line 226, in open
    **kwargs)
  File "rasterio/_io.pyx", line 1131, in rasterio._io.DatasetWriterBase.__init__
  File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: Attempt to create new tiff file 'example.tiff' failed: Is a directory
```

**Comment by ljwolf** [comment]
I'm pretty sure the error you're seeing there is a result of your development directory not being clean. `Attempt to create new tiff file 'example.tiff' failed: Is a directory` looks like an error happening in the filesystem?

I'm cool with having a write statement inside of `bounds2img`, but we should deprecate `bounds2raster` if this lands.

**Comment by uvchik** [comment]
For me it is a little bit different to the `bounds2raster` function because it caches the tiles while `bounds2raster` returns one image file. But if you want I could deprecate it.

I would like to improve the code a little and fix the conflicts but I do not want to spend to much time if you decide to take one of the other approaches (#57, #68, #85). I am fine with any working solution, so who will decide, which approach to take. I think it is good to have less requirements but the other approaches might be more elegant. Sorry, that I missed the existing PRs in the beginning.

@jorisvandenbossche, @darribas and @ljwolf Which way should we go?

**Comment by jorisvandenbossche** [comment]
The joblib based caching is merged, see https://github.com/darribas/contextily/issues/46#issuecomment-516580038 for some context.

**Comment by uvchik** [comment]
With the merged PR #85 it is possible to cache tiles using the following line:

```python
import contextily
contextily.tile.memory.store_backend.location = 'my/cache/path' 
```

This makes this PR mostly obsolete.

**Pull request closed without merging**
