### PR TITLE
adding map search and refactoring

### PR DESCRIPTION
**Pull request by choldgraf**
This is a prototype PR for map searching functionality. It implements a new `Place` class that lets you give a string which will return a given map for that string. It tries to be smart about calculating zoom levels though it lets you specify this explicitly if you want.

I'll add in tests if the basics look good here. I had to do some refactoring in order to get the imports working properly. I hope that's OK! Also added an example to show off how this would work.

LMK!

### CODE REVIEW

**Comment by darribas** [comment]
This looks great, thanks! A couple of questions:

1. Do you think `plot_map` could be generalized to take inputs other than a `Place` object? I'm thinking the output from `bounds2img`. Not crucial for this PR though.
1. The tests are failing on `geopy`, can you add it to the testing suite to make sure things are back in business?
1. Could you add tests for the new functionality?

Thanks!

**Comment by choldgraf** [comment]
Oh yeah - the tests will definitely break because I wanted to make sure you were OK with the API change first :) I'll take a pass at fixing those and adding new tests too

**Comment by choldgraf** [comment]
(FYI, outta town for a few days but I'll get back to this when I get back)

**Comment by choldgraf** [comment]
yo @darribas - just added an example that demoes both the `Place` functionality as well as `bounds2img` along with `plot_map`. I also refactored a little bit and added tests. LMK!

BTW: it'd be cool if there were a little sphinx documentation with this package!

**Comment by choldgraf** [comment]
not sure what the 3.4 error is about...

**Comment by choldgraf** [comment]
ping @darribas , any idea what the error in python 3.4 means? Seems like a dependency may not be installed properly?

**Comment by darribas** [comment]
Thank you very much @choldgraf this is great!!!

A couple of points:

1. On the Sphinx, I agree, it'd be fantastic. Do you have some experience on setting it up? My sense is, once it's going, it's not hard to maintain. Content-wise, we could start by dumping what's in the notebook tutorial. @ljwolf might have some tips on this?
1. On the errors, they seem to be two different ones: 

    - [The first](https://travis-ci.org/darribas/contextily/jobs/248152903#L639) is to do with GDAL it seems. From [here](https://github.com/obspy/obspy/issues/1677), it is suggested to try `conda install icu=58.*`. It might be a solution?
    - [The second](https://travis-ci.org/darribas/contextily/jobs/248152903#L654) one, could it be because it's an import from the tests (it does [say](https://travis-ci.org/darribas/contextily/jobs/248152903#L661) it can't find it), so maybe something like `from .. import tile_providers`? I can't test right now because I don't have access to a development machine but it might be that? I'm not sure why it doesn't fail on 3.5 though...

**Comment by choldgraf** [comment]
on sphinx, I can help set that up. Will do so after this PR is finished up.

For the other stuff, I can play around with travis etc. I've found installing the geo libraries (because of their dependence on other C libraries) to be really finnicky, so maybe there's just a particular set of dependencies needed to get it working.

**Comment by darribas** [comment]
Sounds good @choldgraf. Let's leave Sphinx until we have the new functionality ready. On the fails, I'd say give it a go but if it passes on 2.7/3.5 we could say that's the supported version going forward? It'd be good to know why it fails though...

**Comment by darribas** [comment]
@choldgraf Just checking in here. Have you had a chance to look into the Python3.4 problems? I've identified a bug that precluded `bounds2raster` to work and the PR (#13) is showing very similar error (although it's `libnetcdf` rather than `libgeos`). Upon quick inspection, I've realised [3.5 installs](https://travis-ci.org/darribas/contextily/jobs/274121718#L596)) a much newer version of `rasterio` than [3.4](https://travis-ci.org/darribas/contextily/jobs/274120670#L559). So I'm tempted to skip 3.4 as part of the supported versions, unless you'd found a better approach.

On this, I'm planning on cutting a small release for that fix but, since the release machine will be oiled, I'd be happy to try to get a new one with all of your improvements shortly after. What would be needed for that?

**Comment by choldgraf** [comment]
yo! sorry I got bogged down in the summer conference cycle. I'll spend some time on this today or tomorrow to see where we're at :-)

**Comment by choldgraf** [comment]
hmm....so, it appears that rasterio is trying to import the wrong version of libgeos only on python 3.4. At least as far as I can tell, this is not a contextily issue so much as a rasterio issue. E.g., I just tried:

```
conda create --name python34 python=3.4
conda install -c conda-forge cartopy rasterio
pip install -e path/to/contextily
```
and then doing `import rasterio as rio` fails with the same error...

**Comment by darribas** [comment]
Cool! So we're good to go on this front then? Maybe just clarifying that 3.4 is not supported. Is this PR otherwise good to merge? Keen on trying to cut a release before the start of the (UK) semester (what can go wrong?).

**Comment by choldgraf** [comment]
to my knowledge...yeah this should be good to go :-)  I think it's OK to drop 3.4 support...you can always see if this creates a bunch of issues or something but I doubt many users will really strongly want to use 3.4 over 3.5/6

**Comment by darribas** [comment]
Cool! One more thing, could you please add an example to the [guide](https://github.com/darribas/contextily/blob/master/contextily_guide.ipynb)? That's the resource N.1 people use to check how to do things :) If pressed, we can merge and add later, but I'd rather have it from the beginning.

**Comment by choldgraf** [comment]
how does that look? (just added a little section to the guide)

**Comment by choldgraf** [comment]
yo - just checking to make sure there's nothing I should be working on here...

**Comment by ljwolf** [comment]
Wow, ok, seems like bundling github emails in inbox makes them real hard to track. Sorry I missed this tag. 

I've stumbled through most of the sphinx I've seen before, so I wouldn't've had too much to contribute there. Sorry!

On testing, I'm not sure what the design target for contexily is, but I'd only run tests on 3.6 & latest 3. As far as I can tell, the only "long-term" python in the 3 line is 3.6. They claim it'll get [bugfix support til 2021](https://www.python.org/dev/peps/pep-0494/#lifespan), but 3.5 and 3.4 have [no planned](https://www.python.org/dev/peps/pep-0478/#release-schedule) [releases](https://www.python.org/dev/peps/pep-0429/#release-schedule).

**Comment by darribas** [comment]
Sorry, I don't think so. I've been snowed with the beginning of the academic year (UK time) but will try to cut a release early next week!

**Comment by choldgraf** [comment]
no problem - I'm just going through my open PRs and making sure none of them are blocking because of me!

**Comment by lwasser** [comment]
it would be so useful to have this functionality @darribas !! one of my students is working through this and could use it right now! @wino6687 totally get busy schedules and so appreciative to have libraries like this to use. :)

**Comment by ljwolf** [comment]
@choldgraf if you do have a second, I think one thing you might want to do with this PR would be to drop line 10 from the `.travis.ci` file so that testing is dropped for python 3.4. In the discussion here, it seems that's the consensus, so removing it from the CI would add a marker that this is ready to go. 

@darribas would have final say here, tho, but that'd at least make this a single button push to finish the issue of adding the change & having the "right" CI.

**Comment by choldgraf** [comment]
@darribas gimme the word and I'm happy to do this :-)

**Comment by darribas** [comment]
Sorry again for the delay! Thanks @ljwolf for chipping in and @lwasser for the kind words. Yeah, let's go ahead and remove 3.4 from the CI. I'm going to merge and remove it myself and it's a very minor thing and I'm on it at the minute :-)

**Comment by darribas** [comment]
OK, so with e600b9f we're not supporting 3.4 anymore and tests are back on green light!

**Pull request merged**
